---
- hosts: all
  tasks:
  - name: create file
    file:
      path: /home/ansible/testfile1
      state: touch
  - name: create directory
    file:
      path: /home/ansible/testdir
      state: directory

